// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mainmodule.proxies;

public class FacultatiBraila implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject facultatiBrailaMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MainModule.FacultatiBraila";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		NumeFacultate("NumeFacultate"),
		LinkFacultate("LinkFacultate");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FacultatiBraila(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FacultatiBraila(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject facultatiBrailaMendixObject)
	{
		if (facultatiBrailaMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, facultatiBrailaMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.facultatiBrailaMendixObject = facultatiBrailaMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mainmodule.proxies.FacultatiBraila initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mainmodule.proxies.FacultatiBraila(context, mendixObject);
	}

	public static mainmodule.proxies.FacultatiBraila load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mainmodule.proxies.FacultatiBraila.initialize(context, mendixObject);
	}

	public static java.util.List<mainmodule.proxies.FacultatiBraila> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mainmodule.proxies.FacultatiBraila.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of NumeFacultate
	 */
	public final java.lang.String getNumeFacultate()
	{
		return getNumeFacultate(getContext());
	}

	/**
	 * @param context
	 * @return value of NumeFacultate
	 */
	public final java.lang.String getNumeFacultate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NumeFacultate.toString());
	}

	/**
	 * Set value of NumeFacultate
	 * @param numefacultate
	 */
	public final void setNumeFacultate(java.lang.String numefacultate)
	{
		setNumeFacultate(getContext(), numefacultate);
	}

	/**
	 * Set value of NumeFacultate
	 * @param context
	 * @param numefacultate
	 */
	public final void setNumeFacultate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String numefacultate)
	{
		getMendixObject().setValue(context, MemberNames.NumeFacultate.toString(), numefacultate);
	}

	/**
	 * @return value of LinkFacultate
	 */
	public final java.lang.String getLinkFacultate()
	{
		return getLinkFacultate(getContext());
	}

	/**
	 * @param context
	 * @return value of LinkFacultate
	 */
	public final java.lang.String getLinkFacultate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LinkFacultate.toString());
	}

	/**
	 * Set value of LinkFacultate
	 * @param linkfacultate
	 */
	public final void setLinkFacultate(java.lang.String linkfacultate)
	{
		setLinkFacultate(getContext(), linkfacultate);
	}

	/**
	 * Set value of LinkFacultate
	 * @param context
	 * @param linkfacultate
	 */
	public final void setLinkFacultate(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String linkfacultate)
	{
		getMendixObject().setValue(context, MemberNames.LinkFacultate.toString(), linkfacultate);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return facultatiBrailaMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mainmodule.proxies.FacultatiBraila that = (mainmodule.proxies.FacultatiBraila) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
